# Generated by Django 4.0.4 on 2022-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(related_name='books_in_store', to='core.book'),
        ),
    ]
